/*
 * OmniVoice — Translation Module (NLLB-200 via ONNX Runtime)
 */

package com.omnivoice.onspeak47.pipeline;

import android.content.Context;
import android.icu.text.BreakIterator;
import android.util.Log;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import ai.onnxruntime.OnnxTensor;
import ai.onnxruntime.OnnxValue;
import ai.onnxruntime.OrtEnvironment;
import ai.onnxruntime.OrtException;
import ai.onnxruntime.OrtSession;
import ai.onnxruntime.extensions.OrtxPackage;
import com.omnivoice.onspeak47.util.FileUtils;
import com.omnivoice.onspeak47.util.TensorUtils;

public class TranslationModule {

    private static final String TAG = "TranslationModule";

    private static final String ENCODER_FILE = "encoder_model_int8.onnx";
    private static final String DECODER_FILE = "decoder_model_merged_int8.onnx";
    private static final String VOCAB_FILE = "sentencepiece_bpe.model";
    private static final String LANG_TOKEN_MAP_FILE = "language_token_map.json";

    private static final int MAX_OUTPUT_TOKENS = 256;

    private final OrtEnvironment env;
    private final OrtSession encoderSession;
    private final OrtSession decoderSession;
    private final Tokenizer tokenizer;

    private static final Map<String, String> NLLB_CODES = new HashMap<>();
    static {
        NLLB_CODES.put("vi", "vie_Latn");
        NLLB_CODES.put("en", "eng_Latn");
        NLLB_CODES.put("zh", "zho_Hans");
    }

    public TranslationModule(Context context) throws OrtException {
        env = OrtEnvironment.getEnvironment();

        // Use External Files Dir to avoid C: drive issues
        File baseDir = context.getExternalFilesDir(null);
        if (baseDir == null) {
            baseDir = context.getFilesDir();
        }

        String encoderPath = copyModel(context, baseDir, ENCODER_FILE);
        String decoderPath = copyModel(context, baseDir, DECODER_FILE);
        String vocabPath = copyModel(context, baseDir, VOCAB_FILE);

        // Copy language token map (generated by 02_prune_vocab.py) if present
        copyModelOptional(context, baseDir, LANG_TOKEN_MAP_FILE);

        OrtSession.SessionOptions options = new OrtSession.SessionOptions();
        try {
            options.registerCustomOpLibrary(OrtxPackage.getLibraryPath());
        } catch (OrtException e) {
            Log.e(TAG, "Extensions library not found", e);
        }
        
        options.setOptimizationLevel(OrtSession.SessionOptions.OptLevel.ALL_OPT);

        // Try to use NNAPI for hardware acceleration (NPU/GPU/DSP)
        try {
            options.addNnapi();
            Log.i(TAG, "NNAPI execution provider enabled");
        } catch (OrtException e) {
            Log.w(TAG, "NNAPI not available, using CPU fallback", e);
        }

        encoderSession = env.createSession(encoderPath, options);
        decoderSession = env.createSession(decoderPath, options);

        // Pass the base dir so Tokenizer can find language_token_map.json
        tokenizer = new Tokenizer(vocabPath, baseDir.getAbsolutePath(), Tokenizer.NLLB);
        options.close();

        // Log tokenizer init state for debugging
        if (tokenizer.isReady()) {
            Log.i(TAG, "Tokenizer ready — SP vocab size (dictionaryLength): "
                    + tokenizer.getDictionaryLength());
        } else {
            Log.e(TAG, "Tokenizer FAILED to initialize: " + tokenizer.getInitError());
        }
    }

    public TranslationResult translate(String text, String srcLang, String tgtLang) {
        long startTime = System.currentTimeMillis();
        if (text == null || text.trim().isEmpty()) {
            return new TranslationResult("", 0);
        }

        // Fail fast with a descriptive message if the tokenizer never loaded
        if (!tokenizer.isReady()) {
            String reason = tokenizer.getInitError();
            Log.e(TAG, "Cannot translate — tokenizer not initialized: " + reason);
            return new TranslationResult("[error: tokenizer not loaded — " + reason + "]",
                    System.currentTimeMillis() - startTime);
        }

        String nllbSrc = getNllbCode(srcLang);
        String nllbTgt = getNllbCode(tgtLang);

        ArrayList<String> sentences = splitIntoSentences(text, srcLang);
        StringBuilder result = new StringBuilder();

        for (String sentence : sentences) {
            if (sentence.trim().isEmpty()) continue;
            String translated = translateSentence(sentence, nllbSrc, nllbTgt);
            if (result.length() > 0) result.append(" ");
            result.append(translated);
        }

        long elapsed = System.currentTimeMillis() - startTime;
        return new TranslationResult(result.toString(), elapsed);
    }

    private String translateSentence(String text, String nllbSrc, String nllbTgt) {
        OrtSession.Result encoderResult = null;
        try {
            Tokenizer.TokenizerResult input = tokenizer.tokenize(nllbSrc, nllbTgt, text);
            if (input == null) {
                String reason = tokenizer.getInitError();
                return "[error: tokenization failed"
                        + (reason != null ? " — " + reason : "") + "]";
            }

            OnnxTensor inputIds = TensorUtils.intArrayToTensor(env, input.inputIDs);
            OnnxTensor mask = TensorUtils.intArrayToTensor(env, input.attentionMask);
            Map<String, OnnxTensor> encoderInputs = new HashMap<>();
            encoderInputs.put("input_ids", inputIds);
            encoderInputs.put("attention_mask", mask);

            encoderResult = encoderSession.run(encoderInputs);
            inputIds.close();

            OnnxTensor encoderOutput = (OnnxTensor) encoderResult.get("last_hidden_state").get();

            ArrayList<Integer> outputIds = greedyDecode(encoderOutput, mask, nllbTgt);

            int[] outputArray = new int[outputIds.size()];
            for (int i = 0; i < outputIds.size(); i++) {
                outputArray[i] = outputIds.get(i);
            }
            String translation = tokenizer.decode(outputArray);

            mask.close();
            return translation;
        } catch (OrtException e) {
            Log.e(TAG, "Dịch lỗi", e);
            return "[error]";
        } finally {
            if (encoderResult != null) encoderResult.close();
        }
    }

    /**
     * Greedy decode, matching HuggingFace's greedy_search contract for NLLB/M2M-100.
     *
     * Decoder prefix: [</s> (bos = id 2), <target_lang>]. The whole accumulated
     * sequence is re-fed each step with use_cache_branch=false and empty past, so
     * the model always sees the full context. This is the simplest correct scheme:
     * verified on desktop it yields e.g. "It was a good game today." instead of the
     * single-token-degenerate output from the previous per-step KV-cache loop (which
     * seeded only the lang token and corrupted/reset the cross-attention cache).
     */
    private ArrayList<Integer> greedyDecode(OnnxTensor encoderOutput, OnnxTensor mask, String nllbTgt) throws OrtException {
        final int eosId = tokenizer.pieceToId("</s>");   // NLLB eos == bos == 2
        final int targetLangId = tokenizer.getLanguageID(nllbTgt);

        // Growable decoder input sequence, starting with [bos, target_lang].
        ArrayList<Integer> decoderSeq = new ArrayList<>();
        decoderSeq.add(eosId);
        decoderSeq.add(targetLangId);

        // Names and fixed (empty) shapes for the optional KV-cache inputs.
        boolean hasCacheBranch = false;
        ArrayList<String> decoderPastNames = new ArrayList<>();
        ArrayList<String> encoderPastNames = new ArrayList<>();
        for (String inputName : decoderSession.getInputNames()) {
            if (inputName.equals("use_cache_branch")) {
                hasCacheBranch = true;
            } else if (inputName.startsWith("past_key_values")) {
                if (inputName.contains(".encoder.")) encoderPastNames.add(inputName);
                else decoderPastNames.add(inputName);
            }
        }

        ArrayList<Integer> outputIds = new ArrayList<>();

        for (int step = 0; step < MAX_OUTPUT_TOKENS; step++) {
            // Build fresh empty past tensors each step (branch is off, but inputs must exist).
            Map<String, OnnxTensor> inputs = new HashMap<>();
            OnnxTensor inputSeq = TensorUtils.intArrayToTensor(env, toIntArray(decoderSeq));
            inputs.put("input_ids", inputSeq);
            inputs.put("encoder_hidden_states", encoderOutput);
            inputs.put("encoder_attention_mask", mask);
            if (hasCacheBranch) {
                inputs.put("use_cache_branch", TensorUtils.booleanToTensor(env, false));
            }
            for (String n : decoderPastNames) {
                inputs.put(n, TensorUtils.createFloatTensor(env, new long[]{1, 16, 0, 64}));
            }
            for (String n : encoderPastNames) {
                inputs.put(n, TensorUtils.createFloatTensor(env, new long[]{1, 16, 0, 64}));
            }

            try (OrtSession.Result stepResult = decoderSession.run(inputs)) {
                float[][][] logits = (float[][][]) stepResult.get("logits").get().getValue();
                int next = TensorUtils.argmax(logits[0][logits[0].length - 1]);
                if (next == eosId) {
                    break;                       // done; EOS not appended to output
                }
                outputIds.add(next);
                decoderSeq.add(next);
            } finally {
                // Close every input tensor we created this step (not encoderOutput/mask,
                // which are owned by the caller).
                for (Map.Entry<String, OnnxTensor> e : inputs.entrySet()) {
                    String k = e.getKey();
                    if (!k.equals("encoder_hidden_states") && !k.equals("encoder_attention_mask")) {
                        e.getValue().close();
                    }
                }
            }
        }

        return outputIds;
    }

    private static int[] toIntArray(ArrayList<Integer> list) {
        int[] arr = new int[list.size()];
        for (int i = 0; i < list.size(); i++) arr[i] = list.get(i);
        return arr;
    }

    private ArrayList<String> splitIntoSentences(String text, String langCode) {
        ArrayList<String> sentences = new ArrayList<>();
        Locale locale = langCode.equals("vi") ? new Locale("vi") : Locale.US;
        BreakIterator iterator = BreakIterator.getSentenceInstance(locale);
        iterator.setText(text);
        int start = iterator.first();
        for (int end = iterator.next(); end != BreakIterator.DONE; start = end, end = iterator.next()) {
            sentences.add(text.substring(start, end).trim());
        }
        return sentences;
    }

    private String getNllbCode(String langCode) {
        return NLLB_CODES.getOrDefault(langCode, "vie_Latn");
    }

    /**
     * Copy an asset to the base directory, ignoring errors if it doesn't
     * exist in APK assets (used for optional config files like
     * language_token_map.json).
     */
    private void copyModelOptional(Context context, File baseDir, String assetName) {
        File outFile = new File(baseDir, assetName);
        if (outFile.exists()) return;
        try {
            context.getAssets().open(assetName).close(); // check if exists
            FileUtils.copyAssetToDir(context, assetName, baseDir);
        } catch (java.io.IOException e) {
            Log.d(TAG, "Optional asset not found in APK: " + assetName);
        }
    }

    private String copyModel(Context context, File baseDir, String assetName) {
        File outFile = new File(baseDir, assetName);
        if (!outFile.exists()) {
            FileUtils.copyAssetToDir(context, assetName, baseDir);
        }
        return outFile.getAbsolutePath();
    }

    public static class TranslationResult {
        public final String text;
        public final long processingMs;
        public TranslationResult(String text, long processingMs) {
            this.text = text;
            this.processingMs = processingMs;
        }
    }
}
